apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: fluxcd-demo
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: fluxcd-demo
  targetNamespace: fluxcd-demo
  chart:
    git: git@github.com:c0deltin/springboot-helm-chart.git
    path: helm/springboot-demoweb
    ref: springboot-demoweb
